Repository rcthakuri/ChatGPT-Slack, pull requests merged in 2023-01, with the labels that each got.

#5 Task/3 create python selenium script to update request url in event subscriptions
  .env-sample
  automation/automate/automate_slack_event_subscription.py
  automation/automation_model/__init__.py
  automation/automation_model/selector/slack_selector.py
  requirements.txt
  slack_url_updator/updator.py
Labels: Feature

#7 Task/3 create python selenium script to update request url in event subscriptions
  .env-sample
  automation/automate/automate_slack_event_subscription.py
  automation/automation_model/__init__.py
  automation/automation_model/selector/slack_selector.py
  requirements.txt
  slack_url_updator/updator.py
Labels: Feature

#12 Task/11 Rebuilding project and package hierarchy
  app.py
  chatgpt_slack_lib/__init__.py
  chatgpt_slack_lib/bot/__init__.py
  chatgpt_slack_lib/bot/app_manifest/__init__.py
  chatgpt_slack_lib/bot/app_manifest/manifest.py
  chatgpt_slack_lib/bot/slack_chatgpt.py
  chatgpt_slack_lib/chatgpt_wrapper/__init__.py
  chatgpt_slack_lib/chatgpt_wrapper/chatgpt.py
  chatgpt_slack_lib/depreciated/automation/automate/automate_slack_event_subscription.py
  chatgpt_slack_lib/depreciated/automation/automation_model/__init__.py
  chatgpt_slack_lib/depreciated/automation/automation_model/selector/slack_selector.py
  chatgpt_slack_lib/ngrok_wrapper/__init__.py
  chatgpt_slack_lib/ngrok_wrapper/ngrok.py
  chatgpt_slack_lib/slack_url_updator/updator.py
  chatgpt_slack_lib/utility/__init__.py
  chatgpt_slack_lib/utility/custom_thread.py
  chatgpt_slack_lib/utility/http_client.py
  ngrok_tunnel_updator.py
Labels: enhancement

#16 Task/9 Regenerate slack config token before expire
  .gitignore
  app.py
  chatgpt_slack_lib/app_management/__init__.py
  chatgpt_slack_lib/app_management/app_manifest/__init__.py
  chatgpt_slack_lib/app_management/app_manifest/slack_app_manifest.py
  chatgpt_slack_lib/app_management/authentication/__init__.py
  chatgpt_slack_lib/app_management/authentication/chatgpt_auth.py
  chatgpt_slack_lib/app_management/authentication/slack_auth.py
  chatgpt_slack_lib/app_management/client/__init__.py
  chatgpt_slack_lib/app_management/client/slack/__init__.py
  chatgpt_slack_lib/app_management/client/slack/endpoint/__init__.py
  chatgpt_slack_lib/app_management/client/slack/endpoint/slack_endpoint.py
  chatgpt_slack_lib/app_management/client/slack/slack_client.py
  chatgpt_slack_lib/bot/app_manifest/manifest.py
  chatgpt_slack_lib/bot/slack_chatgpt.py
  chatgpt_slack_lib/ngrok_wrapper/ngrok.py
  chatgpt_slack_lib/slack_url_updator/updator.py
  chatgpt_slack_lib/utility/http_client.py
Labels: Feature

#17 Task/13 prepare documentation for code use for end user
  README.md
Labels: documentation

#19 Develop
  .env-sample
  .gitignore
  README.md
  app.py
  bot/slack_chatgpt.py
  chatgpt_slack_lib/__init__.py
  chatgpt_slack_lib/app_management/__init__.py
  chatgpt_slack_lib/app_management/app_manifest/__init__.py
  chatgpt_slack_lib/app_management/app_manifest/slack_app_manifest.py
  chatgpt_slack_lib/app_management/authentication/__init__.py
  chatgpt_slack_lib/app_management/authentication/chatgpt_auth.py
  chatgpt_slack_lib/app_management/authentication/slack_auth.py
  chatgpt_slack_lib/app_management/client/__init__.py
  chatgpt_slack_lib/app_management/client/slack/__init__.py
  chatgpt_slack_lib/app_management/client/slack/endpoint/__init__.py
  chatgpt_slack_lib/app_management/client/slack/endpoint/slack_endpoint.py
  chatgpt_slack_lib/app_management/client/slack/slack_client.py
  chatgpt_slack_lib/bot/__init__.py
  chatgpt_slack_lib/bot/slack_chatgpt.py
  chatgpt_slack_lib/chatgpt_wrapper/__init__.py
  chatgpt_slack_lib/chatgpt_wrapper/chatgpt.py
  chatgpt_slack_lib/depreciated/automation/automate/automate_slack_event_subscription.py
  chatgpt_slack_lib/depreciated/automation/automation_model/__init__.py
  chatgpt_slack_lib/depreciated/automation/automation_model/selector/slack_selector.py
  chatgpt_slack_lib/ngrok_wrapper/__init__.py
  chatgpt_slack_lib/ngrok_wrapper/ngrok.py
  chatgpt_slack_lib/slack_url_updator/updator.py
  chatgpt_slack_lib/utility/__init__.py
  chatgpt_slack_lib/utility/custom_thread.py
  chatgpt_slack_lib/utility/http_client.py
  ngrok_tunnel_updator.py
  requirements.txt
Labels: Staging

#21 Hotfix/20- Error handling when no config can be generated
  chatgpt_slack_lib/app_management/authentication/slack_auth.py
Labels: hotfix

#23 bug/22- Manifest not updated
  chatgpt_slack_lib/app_management/app_manifest/slack_app_manifest.py
Labels: hotfix

#25 bug/24- Bolt app unable to respond on bot mention
  chatgpt_slack_lib/bot/slack_chatgpt.py
Labels: hotfix

#27 bug/26- Fixed thread issue in `ngrok.py` module
  chatgpt_slack_lib/ngrok_wrapper/ngrok.py
Labels: hotfix
